/**
 *
 *   JIT compiler TLS storage (explicit instantiations).
 *
 *   This file is part of XAD, a comprehensive C++ library for
 *   automatic differentiation.
 *
 *   Copyright (C) 2010-2025 Xcelerit Computing Ltd.
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published
 *   by the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/

#include <XAD/Config.hpp>

#ifdef XAD_ENABLE_JIT

// Mirror XAD's Tape TLS instantiation pattern (see src/Tape.cpp):
// - provide TLS storage in exactly one translation unit
// - emit TLS definitions for all configured XAD modes (to satisfy references from headers)
#include <XAD/ARealDirect.hpp>
#include <XAD/BinaryOperators.hpp>
#include <XAD/FRealDirect.hpp>
#include <XAD/Literals.hpp>
#include <XAD/Tape.hpp>
#include <XAD/UnaryOperators.hpp>

#include <XAD/JITCompiler.hpp>

namespace xad
{

// Define TLS storage for active_jit_ for a given specialization without forcing full class
// template instantiation (we only need the static data member definition for linking).
#define MAKE_JIT_TLS(type)                                                                         \
    template <>                                                                                    \
    XAD_THREAD_LOCAL JITCompiler<type>* JITCompiler<type>::active_jit_ = nullptr;

#define MAKE_JIT_TLS_HIGHER(type)                                                                  \
    template struct type;                                                                          \
    MAKE_JIT_TLS(type)

// 1st order
MAKE_JIT_TLS(float)
MAKE_JIT_TLS(double)

// 2nd order baseline (mirror Tape.cpp)
MAKE_JIT_TLS_HIGHER(AReal<float>)
MAKE_JIT_TLS_HIGHER(AReal<double>)
MAKE_JIT_TLS(XAD_SINGLE_ARG(FReal<float>))
MAKE_JIT_TLS(XAD_SINGLE_ARG(FReal<double>))
MAKE_JIT_TLS_HIGHER(ARealDirect<float>)
MAKE_JIT_TLS_HIGHER(ARealDirect<double>)
MAKE_JIT_TLS_HIGHER(FRealDirect<double>)
MAKE_JIT_TLS_HIGHER(FRealDirect<float>)

// Additional modes generated by CMake (same list as Tape.cpp uses).
// Instantiations.hpp expands MAKE_TAPE_TLS(XAD_SINGLE_ARG(<RealType, N>)) lines.
#define MAKE_TAPE_TLS(type) MAKE_JIT_TLS(type)
#include <XAD/Instantiations.hpp>
#undef MAKE_TAPE_TLS

#undef MAKE_JIT_TLS_HIGHER
#undef MAKE_JIT_TLS

}  // namespace xad

#endif  // XAD_ENABLE_JIT


