name: Benchmark Comparison

on:
  workflow_run:
    workflows:
      - Benchmark Runner
    types:
      - completed

jobs:
  compare:
    name: Compare Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run Reference Benchmark
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd samples/LiborSwaptionPricer
          rm -f output.log || true
          ./LiborSwaptionPricer 50000
          for i in $(seq 1 5); do \
            ./LiborSwaptionPricer 50000 | tee -a output.log; \
          done
          mv output.log libor_benchmark_main.log

      - name: Download PR Benchmark Results
        uses: actions/download-artifact@v3
        with:
          name: libor-benchmark
          path: libor_benchmark_pr.log

      - name: Compare Results
        run: |
          PR_TIME=$(grep "Time" libor_benchmark_pr.log | awk '{print $NF}')
          MAIN_TIME=$(grep "Time" libor_benchmark_main.log | awk '{print $NF}')
          DIFF=$(echo "$MAIN_TIME - $PR_TIME" | bc)
          PERCENT=$(echo "scale=2; ($DIFF / $MAIN_TIME) * 100" | bc)
          echo "Reference Time (Main): $MAIN_TIME"
          echo "PR Time: $PR_TIME"
          echo "Difference: $DIFF seconds"
          echo "Improvement: $PERCENT%"