name: Benchmark Runner

on: 
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  libor:
    name: Libor Swaption Sample
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/foonathan/gcc:12
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Run Benchmark
        run: |
          set -e
          cd build/samples/LiborSwaptionPricer
          rm -f output.log || true
          ./LiborSwaptionPricer 50000
          for i in $(seq 1 5); do \
            ./LiborSwaptionPricer 50000 | tee -a output.log; \
          done

      - name: Upload Benchmark
        uses: actions/upload-artifact@v3
        with:
          name: libor-benchmark
          path: build/samples/LiborSwaptionPricer/output.log